# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 21:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'denied'), (2, 'active'), (3, 'deactivated')], default=0)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_website', models.CharField(blank=True, max_length=100)),
                ('rain_garden', models.BooleanField(default=False)),
                ('stormwater_basin', models.BooleanField(default=False)),
                ('subsurface_storage', models.BooleanField(default=False)),
                ('green_roof', models.BooleanField(default=False)),
                ('permeable_pavement', models.BooleanField(default=False)),
                ('cistern', models.BooleanField(default=False)),
                ('other_retrofit', models.CharField(blank=True, max_length=60)),
                ('ein', models.CharField(max_length=20)),
                ('commercial_activity_license', models.CharField(blank=True, max_length=20)),
                ('should_email_parcel_updates_preference', models.BooleanField(default=False)),
                ('saved_parcel_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('prefer_email', models.BooleanField(default=False)),
                ('prefer_phone', models.BooleanField(default=False)),
                ('rain_garden', models.BooleanField(default=False)),
                ('stormwater_basin', models.BooleanField(default=False)),
                ('subsurface_storage', models.BooleanField(default=False)),
                ('green_roof', models.BooleanField(default=False)),
                ('permeable_pavement', models.BooleanField(default=False)),
                ('cistern', models.BooleanField(default=False)),
            ],
        ),
    ]
