# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_propertymanager_selected_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='propertymanager',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
