# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_propertymanager_add_unsubscribe_token_and_require_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='accepts_contacts',
            field=models.BooleanField(default=True),
        ),
    ]
