# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='building_type',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
