# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_parcel_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_grant_approval',
            field=models.BooleanField(default=False),
        ),
    ]
