# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_grant_approval_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
