# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_approved_at_and_deactivated_at_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_admin_generated_password',
            field=models.BooleanField(default=False),
        ),
    ]
