# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_has_admin_generated_password_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='accepts_contacts',
        ),
    ]
