# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_parcel_accepts_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason_for_denial',
            field=models.TextField(blank=True, default='', null=False),
        ),
    ]
