# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_reason_for_denial_to_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
