# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_website_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_construction_firm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_design_firm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_maintenance_firm',
            field=models.BooleanField(default=False),
        ),
    ]
