# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_collect_vendor_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='stormwater_basin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stormwater_basin',
        ),
    ]
