# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_stormwater_basin'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='accepts_contacts',
            field=models.BooleanField(default=True),
        ),
    ]
